##### image Manipulation

In [1]:
# for image manipulation 
import numpy as np
import imageio.v2 as imageio
from imageio.v2 import imread, imsave
from skimage.transform import resize

# Read a JPEG image into a numpy array 
img = imread(r"C:\Users\Basanta_Atanu\OneDrive\Desktop\Atanu\Atanu_Github\Instrument_Automation\Applying_Machine_Learning\Image_basic_Scipy_ImageProcessing.jpg") # path of the image 
# print(img,img.dtype, img.shape) 

# Tinting the image 
img_tint = img * [1, 0.4, 0.3] 
# print(img_tint)

# Saving the tinted image 
imsave(r"C:\Users\Basanta_Atanu\OneDrive\Desktop\Atanu\Atanu_Github\Instrument_Automation\Applying_Machine_Learning\cat_tinted.jpg", img_tint.astype(np.uint8)) 

# Resizing the tinted image to be 300 x 300 pixels 
img_tint_resize = resize(img_tint, (300, 300))

# # Saving the resized tinted image 
imsave(r"C:\Users\Basanta_Atanu\OneDrive\Desktop\Atanu\Atanu_Github\Instrument_Automation\Applying_Machine_Learning\cat_tinted_resized.jpg", img_tint_resize.astype(np.uint8))


##### Useful reference for classification_report and the confusion matrix
1. https://iamirmasoud.com/2022/06/19/understanding-micro-macro-and-weighted-averages-for-scikit-learn-metrics-in-multi-class-classification-with-example/
2. https://www.geeksforgeeks.org/compute-classification-report-and-confusion-matrix-in-python/

In [2]:
# Python script using Scikit-learn 
# for Decision Tree Classifier 

# Sample Decision Tree Classifier 
from sklearn import datasets 
from sklearn import metrics 
from sklearn.tree import DecisionTreeClassifier 

# load the iris datasets 
dataset = datasets.load_iris() 
# print(dataset)

# fit a CART model to the data 
model = DecisionTreeClassifier() 
model.fit(dataset.data, dataset.target) 
print(model) 

# make predictions 
expected = dataset.target 
predicted = model.predict(dataset.data) 

# summarize the fit of the model 
print(metrics.classification_report(expected, predicted)) 
print(metrics.confusion_matrix(expected, predicted)) 

DecisionTreeClassifier()
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       1.00      1.00      1.00        50
           2       1.00      1.00      1.00        50

    accuracy                           1.00       150
   macro avg       1.00      1.00      1.00       150
weighted avg       1.00      1.00      1.00       150

[[50  0  0]
 [ 0 50  0]
 [ 0  0 50]]


##### Theano

In [4]:
# Python program using Theano 
# for computing a Logistic 
# Function 
# import theano 
# theano.config.optimizer = 'None'
# import theano.tensor as T 
# x = T.dmatrix('x') 
# s = 1 / (1 + T.exp(-x)) 
# logistic = theano.function([x], s) 
# logistic([[0, 1], [-1, -2]]) 

##### TensorFlow

In [6]:
# Python program using TensorFlow 
# for multiplying two arrays 
!pip install tensorflow

# import `tensorflow` 
import tensorflow as tf 

# Initialize two constants 
x1 = tf.constant([1, 2, 3, 4]) 
x2 = tf.constant([5, 6, 7, 8]) 

# Multiply 
result = tf.multiply(x1, x2) 

# Initialize the Session 
sess = tf.Session() 

# Print the result 
print(sess.run(result)) 

# Close the session 
sess.close() 

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


Defaulting to user installation because normal site-packages is not writeable
     ---------------------------------------- 0.0/46.2 kB ? eta -:--:--
     ---------------------------------------- 46.2/46.2 kB 2.2 MB/s eta 0:00:00
   ---------------------------------------- 0.0/377.0 MB ? eta -:--:--
   ---------------------------------------- 0.1/377.0 MB 4.3 MB/s eta 0:01:28
   ---------------------------------------- 0.4/377.0 MB 6.4 MB/s eta 0:00:59
   ---------------------------------------- 1.0/377.0 MB 8.9 MB/s eta 0:00:43
   ---------------------------------------- 2.1/377.0 MB 15.2 MB/s eta 0:00:25
    --------------------------------------- 4.9/377.0 MB 26.1 MB/s eta 0:00:15
    --------------------------------------- 9.4/377.0 MB 40.2 MB/s eta 0:00:10
   - ------------------------------------- 13.5/377.0 MB 110.0 MB/s eta 0:00:04
   - ------------------------------------- 14.8/377.0 MB 108.8 MB/s eta 0:00:04
   - -------------------------------------- 14.9/377.0 MB 72.6 MB/s 

AttributeError: module 'tensorflow' has no attribute 'Session'