<a href="https://colab.research.google.com/github/ghoshatanu857/Instrument_Automation/blob/main/Vector_Magnetometry.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import numpy as np
from plotly.subplots import make_subplots
from plotly import graph_objs as go
import plotly.figure_factory as ff

In [2]:
fig_template = go.layout.Template()
fig_template.layout = {
    'template': 'simple_white+presentation',
    'autosize': False,
    'width': 800,
    'height': 600,
    # 'opacity': 0.2,
    'xaxis': {
        'ticks': 'inside',
        'mirror': 'ticks',
        'linewidth': 1.5+0.5,
        'tickwidth': 1.5+0.5,
        'ticklen': 6,
        'showline': True,
        'showgrid': False,
        'zerolinecolor': 'white',
        },
    'yaxis': {
        'ticks': 'inside',
        'mirror': 'ticks',
        'linewidth': 1.5+0.5,
        'tickwidth': 1.5+0.5,
        'ticklen': 6,
        'showline': True,
        'showgrid': False,
        'zerolinecolor': 'white'
        },
    'font':{'family':'mathjax',
            'size': 22,
            }
}

In [190]:
def magField(current,distance):
  field = (4*np.pi*1e-7*current)/(2*np.pi*distance)
  return field

In [400]:
# def circle(inner_r,outer_r,circle_points,line_points):
#   x_array=[]; y_array=[]
#   x_array.append([points*np.cos(_points) for points,_points in zip(line_points,circle_points)])
#   y_array.append([points*np.sin(_points) for points,_points in zip(line_points,circle_points)])
#   return x_array, y_array

In [399]:
# wire_radius = 25e-6; distance = 100e-6; wire_current = 10
# linear_density = 2; init_angle = -np.pi; final_angle = 0

# linear_points = np.linspace(wire_radius, distance, linear_density)
# circular_points=[]; circular_angles=[]
# [circular_points.append(int(circular_density*2+2)) for circular_density in range(linear_density)]
# circular_points = np.array(circular_points)
# [circular_angles.append(np.linspace(init_angle, final_angle,_points)) for _points in circular_points]
# # circular_angles = np.array(circular_angles)

# mag_field = magField(current=wire_current,distance= linear_points)
# x_points, y_points = circle(wire_radius, distance, circular_angles,line_points=mag_field)

In [401]:
def circle(inner_r,outer_r,circle_points,line_points):
  x_array=[]; y_array=[]
  x_array.append([points*np.cos(circle_points) for points in line_points])
  y_array.append([points*np.sin(circle_points) for points in line_points])
  return np.squeeze(np.array(x_array)), np.squeeze(np.array(y_array))

In [402]:
wire_radius = 25e-6; distance = 100e-6; wire_current = 10
linear_density = 10; circular_density = 20
init_angle = -np.pi; final_angle = 0

linear_points = np.linspace(wire_radius, distance, linear_density)
circular_points = np.linspace(init_angle, final_angle, circular_density)

mag_field = magField(current=wire_current,distance= linear_points)
x_points, y_points = circle(wire_radius, distance, circular_points,line_points=mag_field)

In [404]:
mag_field,x_points[0],y_points[0]

(array([0.08      , 0.06      , 0.048     , 0.04      , 0.03428571,
        0.03      , 0.02666667, 0.024     , 0.02181818, 0.02      ]),
 array([-0.08      , -0.0789089 , -0.07566538, -0.0703579 , -0.06313124,
        -0.05418253, -0.04375585, -0.03213563, -0.01963884, -0.00660635,
         0.00660635,  0.01963884,  0.03213563,  0.04375585,  0.05418253,
         0.06313124,  0.0703579 ,  0.07566538,  0.0789089 ,  0.08      ]),
 array([-9.79717439e-18, -1.31675672e-02, -2.59759575e-02, -3.80757914e-02,
        -4.91370170e-02, -5.88579129e-02, -6.69733183e-02, -7.32618661e-02,
        -7.75520213e-02, -7.97267594e-02, -7.97267594e-02, -7.75520213e-02,
        -7.32618661e-02, -6.69733183e-02, -5.88579129e-02, -4.91370170e-02,
        -3.80757914e-02, -2.59759575e-02, -1.31675672e-02,  0.00000000e+00]))

In [306]:
# # Plotting the Fitted Curve
# fig = go.Figure()
# [fig.add_scatter(x=x_circle,y=y_circle,mode='lines') for i,(x_circle,y_circle) in enumerate(zip(x_points,y_points))]
# fig.update_layout(template = fig_template,width=800,height=600)
# fig.show()

In [385]:
x_points,list(reversed(x_points[0])),x_points[0][::-1]

([[array([-0.08,  0.08]), array([-0.02, -0.01,  0.01,  0.02])]],
 [array([-0.02, -0.01,  0.01,  0.02]), array([-0.08,  0.08])],
 [array([-0.02, -0.01,  0.01,  0.02]), array([-0.08,  0.08])])

In [398]:
mylist=[1,2]
[ -x for x in mylist]

[-1, -2]

In [405]:
x=x_points;y=y_points;u=-y[::-1];v=x[::-1]
fig = ff.create_quiver(x, y, u, v, scale=.1, arrow_scale=0.2,
                       scaleratio=0.7,angle=np.pi/9,line=dict(width=1.5,color='black' ))
fig.add_trace(go.Scatter(x = [0], y = [0], mode = 'markers', marker_size = 10))
fig.update_layout(template = fig_template,width=800,height=600)
fig.show()